# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2608f9cb2a97b2f2b5cf26ba73716f50"
name = "StoreForge Migration"
application_url = "https://storeforge.site/dashboard/migrate"
embedded = false

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_customers,read_discounts"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://storeforge.site/api/migration/shopify/callback",
  "http://localhost:3000/api/migration/shopify/callback"
]
